---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7.4
    transport:
      name: ssh
      username: vagrant
      password: vagrant
    driver:
      box: bento/centos-7.4
      memory: 1024
      cpus: 1

  - name: azwin
    transport:
      name: winrm
      username: vagrant
      password: vagrant
    driver:
      name: azurerm
    driver_config:
      subscription_id: '9db13c96-62ad-4945-9579-74aeed296e48'
      location: East US 2
      machine_size: Standard_D4s_v3
      image_urn: MicrosoftSQLServer:SQL2016SP1-WS2016:SQLDEV:latest
      data_disks:
        - lun: 0
          disk_size_gb: 979
      vnet_id: /subscriptions/9db13c96-62ad-4945-9579-74aeed296e48/resourceGroups/AZ-RG-Network/providers/Microsoft.Network/virtualNetworks/AZ-VN-EastUS2-01
      subnet_id: AZ-SN-back
      vm_name: azw-kit-sql-01

  - name: trek/Windows2016
    os_type: windows
    shell_type: powershell
    communicator: winrm
    transport:
      name: winrm
      username: vagrant
      password: vagrant
    driver:
      name: vagrant
      box: trek/Windows2016
      box_url: https://aztrksaslh00public01.blob.core.windows.net/vagrant/windows/2016/windows2016min-virtualbox.box
      network:
        - ['private_network', {ip: '192.168.57.11'}]

suites:
  - name: default
    run_list:
      - recipe[cb_dvo_chefclient::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:  
    driver:
      network:
        - ['private_network', {ip: '192.168.57.10'}]
