---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 13.8.5
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7.3
    transport:
      name: ssh
      username: vagrant
      password: vagrant
    driver:
      box: bento/centos-7.3
      memory: 1024
      cpus: 1
    attributes:

suites:
  - name: default
    run_list:
      - recipe[cb_dvo_chefClient::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:  
    driver:
      network:
        - ['private_network', {ip: '192.168.57.10'}]
