---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7.4
    transport:
      name: ssh
      username: vagrant
      password: vagrant
    driver:
      box: bento/centos-7.4
      memory: 1024
      cpus: 1
    attributes:

suites:
  - name: default
    run_list:
      - recipe[cb_dvo_chefClient::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
      dvo_user:
        use: "linux"
        ALM_environment: "local"
      dvo:
        cloud_service_provider:
          name: "local"        
    driver:
      network:
        - ['private_network', {ip: '192.168.57.10'}]
